// Package cliwrapcfg generates a cliwrap.yaml that supervises buddy daemon.
//
// Used by `buddy install --with-cliwrap` (M4). v0.1 ships only the generator;
// install wiring lands in M4.
//
// We deliberately emit YAML by string template rather than importing a YAML
// library: the schema is tiny, vendor stability matters, and string output is
// trivially diffable in tests.
package cliwrapcfg

import (
	"fmt"
	"strings"
)

// Spec is the user-facing config we accept.
type Spec struct {
	BuddyBinary  string // absolute path to the `buddy` binary
	DBPath       string // passed to `buddy daemon run --db <path>`
	RuntimeDir   string // cliwrap runtime dir (sockets, WAL). default: "$HOME/.buddy/cliwrap"
	MaxRestarts  int    // cliwrap restart cap. default: 5
	BackoffSecs  int    // exponential backoff base. default: 2
	StopTimeoutS int    // graceful SIGTERM grace window. default: 5
}

// Defaults applies fallbacks for zero-valued fields.
func (s *Spec) Defaults() {
	if s.MaxRestarts == 0 {
		s.MaxRestarts = 5
	}
	if s.BackoffSecs == 0 {
		s.BackoffSecs = 2
	}
	if s.StopTimeoutS == 0 {
		s.StopTimeoutS = 5
	}
}

// Render returns a cliwrap.yaml document supervising one buddy daemon.
func Render(s Spec) (string, error) {
	if s.BuddyBinary == "" {
		return "", fmt.Errorf("BuddyBinary required")
	}
	s.Defaults()

	args := []string{`"daemon"`, `"run"`}
	if s.DBPath != "" {
		args = append(args, `"--db"`, fmt.Sprintf("%q", s.DBPath))
	}
	argsList := strings.Join(args, ", ")

	runtimeDir := s.RuntimeDir
	if runtimeDir == "" {
		runtimeDir = "${HOME}/.buddy/cliwrap"
	}

	return fmt.Sprintf(`# Auto-generated by buddy. Edit by hand only if you know what you're doing —
# `+"`buddy install --with-cliwrap`"+` will overwrite this file.
version: "1"
runtime:
  dir: %s
  debug: info
groups:
  - name: buddy
    processes:
      - id: buddy-daemon
        name: Buddy Daemon
        command: %s
        args: [%s]
        restart: on_failure
        max_restarts: %d
        restart_backoff: %ds
        stop_timeout: %ds
`, runtimeDir, s.BuddyBinary, argsList, s.MaxRestarts, s.BackoffSecs, s.StopTimeoutS), nil
}
